image: node:latest

stages:
  - build
  - test

build_front_end:
  stage: build
  script:
    - cd frontend
    - npm install
    - CI=false npm run-script build

postman_tests:
  stage: test
  image:
    name: postman/newman:alpine
    entrypoint: [""]
  script:
    - cd backend
    - newman --version
    - newman run collection.json