image: node:latest

stages:
  - build
  - test

# TEST DECLARATIONS

build_frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - CI=false npm run-script build


test_frontend_jest:
  stage: test
  script:
    - cd frontend
    - npm install
    - CI=true npm test


test_frontend_gui:
  stage: test
  image: python:3.10
  script:
  - cd frontend

  # code in hyphens is from GeoJobs for running selenium
  # ---
  - pip install --upgrade pip
  - pip install --no-cache-dir -r ./gui_tests/requirements.txt
  - apt-get update -q -y
  - apt-get --yes install libnss3
  - apt-get --yes install libgconf-2-4
  - apt-get install libx11-xcb1

  # Add chrome to container
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - apt-get update -q -y 
  - apt-get install -y google-chrome-stable

  # Download and unzip the chromedriver
  - apt-get install -yqq unzip
  - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
  - unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
  # ---

  # Run selenium tests
  - python3 guitests.py


test_postman:
  stage: test
  image:
    name: postman/newman:alpine
    entrypoint: [""]
  script:
    - cd backend
    - newman --version
    - newman run collection.json


test_backend:
  stage: test
  image: python:3.6-stretch
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - make pytests