@startuml

    entity College {
        id: Integer <<PK>>
        --
        city: String(70)
        name: String(40)
        zip: Integer
        latitude: Double
        longitude: Double
        admission_rate: Double
        ranking: Integer
        tuition: Integer
    }

    entity College_Image {
        id: BigInteger <<PK>>
        --
        college_id: BigInteger <<FK>>
        img_url: String(200)
    }

    entity Housing_Unit {
        id: String(65) <<PK>>
        --
        apt_id: String(65) <<FK>>
        img_url: String(200)
    }

    entity Job {
        id: BigInteger <<PK>>
        --
        city_id: Integer <<FK>>
        company: String(40)
        title: String(70)
        category: String(30)
        url: String(150)
        salary_min: Integer
        salary_max: Integer
        latitude: Float
        longitude: Float
        description: String(550)
        created: DateTime
        img_url: String(200)
    }

    City }o--o{city_tag_link
    Tag }o--o{ city_tag_link
    City ||-|{ Apartment
    City ||-|{ Job
    Apartment ||--o{ ApartmentImage

@enduml